### ISSUE TITLE
If a drop down GUI was made for klipper configuration it would take off like a rocket. marlin who?

### ISSUE THREAD

**Issue by Crunch69** [mmone/OctoprintKlipperPlugin#7] opened 2018-07-04 16:54 UTC
If a drop down GUI was made for klipper configuration it would take off like a rocket. The user would just have to select his hotend , extruder, the probe and it would build the cfg file for you.  Also add a user guide that is simple and built in.

**Comment by mmone** [comment] 2018-07-04 21:29
This is a duplicate of #6

**Comment by mmone** [comment] 2018-07-17 14:08
Closing this in favor of the duplicate

**Comment by mmone** [comment] 2018-07-17 14:08
Closing

**Closed by mmone** 2018-07-17 14:08 UTC
Labels: duplicate
